import { Document, Model, model, Schema } from "mongoose";
import { addJudgeTask } from "../redis";
import { Problem } from "./problem";

export enum SolutionResult {
    WaitingJudge,            // Wating Judge
    Judging,                 // Judging
    Skipped,                 // Skipped
    Accepted,                // Accepted
    WrongAnswer,             // Wrong Answer
    TimeLimitExceeded,       // Time Limit Exceeded
    MemoryLimitExceeded,     // Memory Limit Exceeded
    RuntimeError,            // Runtime Error
    CompileError,            // Compile Error
    PresentationError,       // Presentation Error
    JudgementFailed,         // Judgement Failed (Judge program error)
    SystemError,             // System Error     (Judge framwork & Judge plugin error)
    OtherError,              // Other Error
}

export interface ISolutionModel extends Document {
    problem: string;
    files: string[];
    status: SolutionResult;
    score: number;
    log?: string;
    contest: string;
    created: Date;
    owner: string;
    public: boolean;
    judge(): Promise<void>;
}

export let SolutionSchema: Schema = new Schema(
    {
        problem: {
            type: String,
            required: true,
        },
        files: {
            type: [String],
            required: true,
        },
        status: {
            type: Number,
            required: true,
            default: SolutionResult.WaitingJudge,
            min: 0,
            max: 12,
        },
        score: {
            type: Number,
            required: true,
            default: 0,
            min: 0,
            max: 100,
        },
        // Readonly - auto generated by system
        contest: {
            type: String,
            required: true,
        },
        log: String,
        created: Date,
        owner: {
            type: String,
            required: true,
        },
        public: {
            type: Boolean,
            required: true,
            default: true,
        },
    },
);

SolutionSchema.methods.judge = async function() {
    const self = this as ISolutionModel;
    const channel = (await Problem.findById(self.problem).select("channel")).channel;
    if (!channel) { return; }
    self.status = SolutionResult.WaitingJudge;
    await self.save();
    await addJudgeTask(self.id, channel);
};

SolutionSchema.pre("save", function(next) {
    const This = this as ISolutionModel;
    if (!This.created) {
        This.created = new Date();
    }
    next();
});

export const Solution: Model<ISolutionModel> = model<ISolutionModel>("Solution", SolutionSchema);
